name: CML
on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3

      - name: Install Jupyter and required Python libraries
        run: |
          pip install jupyter
          pip install -r requirements.txt

      - name: Convert Jupyter Notebook to Python script
        run: jupyter nbconvert --to script Notebook.ipynb

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python Notebook.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo '## Performance' > report.md
          cat results.txt >> report.md
          echo '![](./actual_vs_predicted.png "Predicted vs Actual")' >> report.md
          cml comment create report.md 
