name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python script.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          r2_score=$(grep -oP '(?<=R2 Score: ).*' results.txt)
          mae=$(grep -oP '(?<=Mean Absolute Error \(MAE\): ).*' results.txt)
          mse=$(grep -oP '(?<=Mean Squared Error \(MSE\): ).*' results.txt)
          
          echo "## Performance" > report.md
          echo "R2 Score: $r2_score" >> report.md
          echo "Mean Absolute Error (MAE): $mae" >> report.md
          echo "Mean Squared Error (MSE): $mse" >> report.md
          echo "![](./actual_vs_predicted.png \"Predicted vs Actual\")" >> report.md
          cml comment create report.md
